INSERT INTO series (title, author_id, subgenre_id) VALUES ("Harry Potter", 1, 1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("Lord of the RIngs", 2, 2);
INSERT INTO subgenres (name) VALUES ("Magic");
INSERT INTO subgenres (name) VALUES ("Fantasy");
INSERT INTO authors (name) VALUES ("J.K. Rowlings");
INSERT INTO authors (name) VALUES ("Somebody");
INSERT INTO books (title, year, series_id) VALUES ("Goblet of Fire", 1998, 1);
INSERT INTO books (title, year, series_id) VALUES ("Deathly Hollows", 2005, 1);
INSERT INTO books (title, year, series_id) VALUES ("Azkaban", 2000, 1);
INSERT INTO books (title, year, series_id) VALUES ("Hobbit", 1999, 2);
INSERT INTO books (title, year, series_id) VALUES ("2nd Breakfast", 2006, 2);
INSERT INTO books (title, year, series_id) VALUES ("The third book", 2009, 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Harry", "ello chump", "human", 1);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Ron", "hey harry", "human", 1);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Dobby", "free elf!", "elf", 1);
INSERT INTO characters (name, motto, species, author_id) VALUES ("That Fat Guy", "yer a wizard harry", "giant", 1);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Gandalf", "you shall not pass", "wizard", 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Smeagol", "my preciouss", "creepy thing", 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Biblo", "What??", "hobbit", 2);
INSERT INTO characters (name, motto, species, author_id) VALUES ("Robin hood", "ya dummy", "human", 2);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (2,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (2,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (2,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (2,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (2,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (2,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (2,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (2,1);
